# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: 'v2.5.1' # Use the sha / tag you want to point at
    hooks:
      - id: prettier

  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: 'v8.6.0' # Use the sha / tag you want to point at
    hooks:
      - id: eslint
        files: \.([jt]sx?|vue)$ # *.js, *.jsx, *.ts, *.tsx and *.vue
        types: [file]
        additional_dependencies:
          - eslint@8.6.0
          - typescript@4.5.4
          - '@typescript-eslint/eslint-plugin@5.9.0'
          - '@typescript-eslint/parser@5.9.0'
          - eslint-plugin-vue@8.2.0
          - vue-eslint-parser@8.0.1
          - jest@27.4.7
          - eslint-plugin-jest@25.3.4
          - eslint-config-prettier@8.3.0
